name: build_and_test

on:
  pull_request:
    branches: [ release ]

jobs:
  build:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code from the main branch
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
        with:
          output-file-cache : build_dir
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest